dist: xenial
language: minimal

git:
  quiet: true
  submodules: false

branches:
  only:
  - master
  - deploy

env:
# Carefull, also set it in the deploy section!
- NOTES_FILE=main

services:
- docker

script:
- docker run --rm -v $(pwd):/notes blang/latex /bin/bash -c "cd /notes; ./build.sh $NOTES_FILE"
- "./test.sh $NOTES_FILE"

deploy:
  provider: releases
  api_key:
    secure: xLTTHBhY4pJEtQNPbXixoXggiLjpZL+qgVfptQ0WzS3qhlVWB5FMdzojxKaWDSegHVktW/GoIGbzatr966TlQ+zB3SqhnNfJ6w1e0YxqzzMwkoCkmEhOyuFhCGPK4WWRqr+/ACakN5PV98F8Og80LO+dP5ARJ3+IZzAJh72XdRodkGAarOrTr3i+I5a4plBe7H9mCTCBy4N0j1RYfKhJC3YLD84MCS8gAXwmZWkoViBtrWVItPFvqY6PjMShedulbIxMQQgsc1mMI6Sq1htSx+o5qUuc+vapzPXzXHLfkauZmkkv0+gN5mVsduO8iCSh6tpxv/QQcYoZrQpCF/uWMX3ysL+D5JpRbaz6XB9ykrGdwSH5sh2UXtePYX0bd2RbpVESocCi6Ok91uIZb87l0Kfcjn/1sVlGoEMlP4sspgaWBXB7tNeWQnHxlfBYB+EJo1jhQqasVIKtdzYMa+MJMfFRcVuKd2aKi/Pwr71/3rGqf8Bq/BjpelINlDzswLU3/rLOe2hHIsCocysTRjWfYG8o18Q9oW5i6x3H615aAtlFdDWbwNQQMSXjfyx8PMw57tjut9X1/wNgeYT3dv2PibiSOp9BkcJLdgmURoEAcnCVvJ7tn5JCEFxFGyT8TwvMLRdCdWUa2jP4iLxa+OBKyOvxJv6Vg1bh9TbJdHUj8TY=
  file: main.pdf
  skip_cleanup: true
  on:
    repo: icl-notes/m1j2
